export default {
  splash:  require('../assets/images/03.jpg'),
  logowhite:require('../assets/images/logowhite.jpg'),

  
  card:require('../assets/images/splash.png'),
  logo: require('../assets/images/logo.png'),
  beaanaLogo:require('../assets/images/splashtitle.jpg'),
  bg: require('../assets/images/bg.png'),
  login: require('../assets/images/login.png'),
  forget: require('../assets/images/forget.png'),
  verify: require('../assets/images/verify.png'),
  home: require('../assets/images/home.png'),
  magnifier: require('../assets/images/magnifier.png'),
  profile: require('../assets/images/profile.png'),
  profileIcon: require('../assets/images/profileIcon.png'),
  support: require('../assets/images/support.png'),  
  about: require('../assets/images/about.png'),
  back: require('../assets/images/back.png'),
  cart: require('../assets/images/cart.png'),
  wishlist: require('../assets/images/wishlist.png'),
  wishlist2: require('../assets/images/wishlist2.png'),
  edit: require('../assets/images/edit.png'),
  call: require('../assets/images/call.png'),
  cross: require('../assets/images/cross.png'),
  account: require('../assets/images/Account.png'),
  orders: require('../assets/images/orders.png'),
  categories: require('../assets/images/categories.png'),
  wishlist: require('../assets/images/wishlist.png'),
  notification: require('../assets/images/notification.png'),
  setting: require('../assets/images/setting.png'),
  support: require('../assets/images/support.png'),
  about1: require('../assets/images/about.png'),
  enter: require('../assets/images/enter.png'),
  cross1: require('../assets/images/cross1.png'),
  menu: require('../assets/images/menu.png'),
  shopnow: require('../assets/images/shopnow.png'),
  saddle: require('../assets/images/saddle.png'),
  bag: require('../assets/images/bag.png'),
  women: require('../assets/images/women.png'),
  girl: require('../assets/images/girl.png'),
  men: require('../assets/images/men.png'),
  kids: require('../assets/images/kids.png'),
  beauty: require('../assets/images/beauty.png'),
  women1: require('../assets/images/women1.png'),
  shop1: require('../assets/images/shop1.png'),
  men1: require('../assets/images/men1.png'),
  kids1: require('../assets/images/kids1.png'),
  beauty1: require('../assets/images/beauty1.png'),
  dress1: require('../assets/images/dress1.png'),
  dress2: require('../assets/images/dress2.png'),
  dress3: require('../assets/images/dress3.png'),
  dress4: require('../assets/images/dress4.png'),
  star1: require('../assets/images/star1.png'),
  star2: require('../assets/images/star2.png'),
  star3: require('../assets/images/star3.png'),
  star4: require('../assets/images/star4.png'),
  back: require('../assets/images/back.png'),
  share: require('../assets/images/share.png'),
  addcart: require('../assets/images/addcart.png'),
  delete: require('../assets/images/delete.png'),
  plus: require('../assets/images/plus.png'),
  down: require('../assets/images/down.png'),
  cartImg1: require('../assets/images/cartImg1.png'),
  cartImg2: require('../assets/images/cartImg2.png'),
  tax: require('../assets/images/tax.png'),
  productImg: require('../assets/images/productImg.png'),
  up: require('../assets/images/up.png'),
  add: require('../assets/images/add.png'),
  call: require('../assets/images/call.png'),
  edit: require('../assets/images/edit1.png'),
  check: require('../assets/images/check.png'),
  point1: require('../assets/images/point1.png'),
  point2: require('../assets/images/point2.png'),
  creditcard1: require('../assets/images/creditcard1.png'),
  cod1: require('../assets/images/cod1.png'),
  netbanking1: require('../assets/images/netbanking1.png'),
  order: require('../assets/images/order.png'),
  search1: require('../assets/images/search1.png'),
  arrow: require('../assets/images/arrow.png'),
  check1: require('../assets/images/check1.png'),
  home1: require('../assets/images/home1.png'),
  category1: require('../assets/images/category1.png'),
  order1: require('../assets/images/order1.png'),
  profile1: require('../assets/images/profile1.png'),
  profileImg: require('../assets/images/profileImg.png'),
  editprofile: require('../assets/images/editprofile.png'),
  edit2: require('../assets/images/edit2.png'),
  rimg: require('../assets/images/rimg.png'),
  arrow2: require('../assets/images/arrow2.png'),
  down2: require('../assets/images/down2.png'),
  cross3: require('../assets/images/cross3.png'),
  minus: require('../assets/images/minus.png'),
  sale: require('../assets/images/sale.png'),
  sale1: require('../assets/images/sale1.png'),
  salepro: require('../assets/images/salepro.png'),
  salepro1: require('../assets/images/salepro1.png'),
  timer:require('../assets/images/timer.png'),
  logout:require('../assets/images/logout.png'),
  toggle:require('../assets/images/toggle.png'),
  redirect:require('../assets/images/redirect.png')
};
